language: php

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - gdb
      - re2c

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    #- vendor
    - $HOME/.ccache
    - $HOME/.composer/cache

env:
  global:
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"
    - PATH="$PATH:~/bin"

before_install:
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/phpize /usr/bin/
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/php-config /usr/bin/
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1,2)"

install:
  - composer self-update -q
  - travis_retry composer --prefer-source install
  - bash unit-tests/_ci/install_prereqs.sh
  - bash unit-tests/_ci/install_zephir.sh
  - '(zephir fullclean && zephir generate)'

before_script:
  - (export PRE_PHP_INCLUDES=`php-config --includes`; cd ext/; for file in `find kernel -name "*.h"`; do $CC "$file" -I. $PRE_PHP_INCLUDES -o "$file.ghc"; done)
  - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -DZEPHIR_RELEASE=1"; /usr/bin/phpize &> /dev/null && ./configure --silent --enable-volt &> /dev/null && make --silent -j4 &> /dev/null && make --silent install)
  - phpenv config-add unit-tests/_ci/volt.ini
  - php --ri volt
  - php -m
  - pecl list
  - ulimit -c unlimited -S || true
  - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null
  - echo "opcache.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit --bootstrap unit-tests/_ci/phpunit.php --debug unit-tests/

after_failure:
  - bash unit-tests/_ci/after_failure.sh

notifications:
  email:
    - dreamsxin@qq.com
